version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki:z
    ports:
      - '3030:3030'
    expose:
      - '3030'
    environment:
      ADMIN_PASSWORD: 'admin'

  fuseki_test:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki_test
    volumes:
      - ./data/fuseki_test:/fuseki:z
    ports:
      - '3040:3030'
    expose:
      - '3040'
    environment:
      ADMIN_PASSWORD: 'admin'

  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
    restart: on-failure

  redis:
    image: redis
    container_name: redis
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    command: ['redis-server', '--appendonly', 'yes']

  arena:
    build: ./arena
    container_name: arena
    restart: always
    volumes:
      - ./arena/config:/opt/arena/src/server/config
    depends_on:
      - redis
    ports:
      - '4567:4567'
    expose:
      - '4567'
    environment:
      REDIS_HOST: 'redis'
